import type { CountryData } from "../types";
import { generateCpf } from "../../../routes/tools/cpf/logic";
import { generateCnpj } from "../../../routes/tools/cnpj/logic";

const br: CountryData = {
  id: "br",
  flag: "🇧🇷",
  firstNames: [
    "Ana",
    "Bruno",
    "Carla",
    "Diego",
    "Eduarda",
    "Felipe",
    "Gabriela",
    "Henrique",
    "Isabela",
    "João",
    "Larissa",
    "Mateus",
    "Natália",
    "Otávio",
    "Paula",
    "Rafael",
    "Sabrina",
    "Thiago",
    "Vanessa",
    "Wagner",
    "Yasmin",
    "Zélia",
    "Amanda",
    "Carlos",
    "Daniela",
    "Eduardo",
    "Fernanda",
    "Gustavo",
    "Helena",
    "Igor",
    "Juliana",
    "Lucas",
    "Mariana",
    "Nicolas",
    "Olívia",
    "Pedro",
    "Renata",
    "Sérgio",
    "Tatiane",
    "Úrsula",
  ],
  lastNames: [
    "Silva",
    "Santos",
    "Oliveira",
    "Souza",
    "Rodrigues",
    "Ferreira",
    "Alves",
    "Pereira",
    "Lima",
    "Gomes",
    "Costa",
    "Ribeiro",
    "Martins",
    "Carvalho",
    "Almeida",
    "Lopes",
    "Sousa",
    "Fernandes",
    "Vieira",
    "Barbosa",
    "Rocha",
    "Dias",
    "Nascimento",
    "Andrade",
    "Moreira",
    "Nunes",
    "Marques",
    "Machado",
    "Mendes",
    "Freitas",
    "Cardoso",
    "Ramos",
  ],
  states: [
    "AC",
    "AL",
    "AP",
    "AM",
    "BA",
    "CE",
    "DF",
    "ES",
    "GO",
    "MA",
    "MT",
    "MS",
    "MG",
    "PA",
    "PB",
    "PR",
    "PE",
    "PI",
    "RJ",
    "RN",
    "RS",
    "RO",
    "RR",
    "SC",
    "SP",
    "SE",
    "TO",
  ],
  cities: [
    "São Paulo",
    "Rio de Janeiro",
    "Belo Horizonte",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Curitiba",
    "Manaus",
    "Recife",
    "Porto Alegre",
    "Goiânia",
    "Belém",
    "Guarulhos",
    "Campinas",
    "São Luís",
    "Maceió",
    "Natal",
    "Teresina",
    "Campo Grande",
    "João Pessoa",
    "Osasco",
    "Santo André",
    "São Bernardo do Campo",
    "Jaboatão dos Guararapes",
    "Contagem",
  ],
  domains: [
    "gmail.com",
    "hotmail.com",
    "outlook.com",
    "yahoo.com.br",
    "uol.com.br",
    "terra.com.br",
  ],
  phoneMask: "(XX) 9XXXX-XXXX",
  postalCodeMask: "XXXXX-XXX",
  fieldI18nKeys: {
    name: "nome",
    cpf: "cpf",
    cnpj: "cnpj",
    email: "email",
    phone: "telefone",
    postalCode: "cep",
    state: "estado",
    city: "cidade",
  },
  docs: {
    cpf: { generate: () => generateCpf(true), mono: true },
    cnpj: { generate: () => generateCnpj(true), mono: true },
  },
};

export default br;
