import type { CountryData } from "../types";

const jp: CountryData = {
  id: "jp",
  flag: "🇯🇵",
  firstNames: [
    "Ren",
    "Hinata",
    "Sota",
    "Yui",
    "Haruto",
    "Sakura",
    "Yuto",
    "Riko",
    "Riku",
    "Aoi",
    "Sora",
    "Mei",
    "Yamato",
    "Mio",
    "Taiga",
    "Rin",
    "Haruki",
    "Yuna",
    "Asahi",
    "Miyu",
    "Itsuki",
    "Hana",
    "Shota",
    "Koharu",
    "Kaito",
    "Nanami",
    "Sosuke",
    "Ayaka",
    "Takumi",
    "Rio",
    "Ryo",
    "Yuzuki",
    "Daiki",
    "Kanon",
    "Minato",
    "Moe",
    "Kenta",
    "Miku",
    "Hiroto",
    "Nagi",
  ],
  lastNames: [
    "Sato",
    "Suzuki",
    "Takahashi",
    "Tanaka",
    "Watanabe",
    "Ito",
    "Yamamoto",
    "Nakamura",
    "Kobayashi",
    "Kato",
    "Yoshida",
    "Yamada",
    "Sasaki",
    "Yamaguchi",
    "Saito",
    "Matsumoto",
    "Inoue",
    "Kimura",
    "Hayashi",
    "Shimizu",
    "Yamazaki",
    "Mori",
    "Abe",
    "Ikeda",
    "Hashimoto",
    "Yamashita",
    "Ishikawa",
    "Nakajima",
    "Maeda",
    "Fujita",
    "Ogawa",
    "Goto",
    "Okada",
    "Hasegawa",
    "Murakami",
    "Kondo",
    "Ishii",
    "Nishimura",
    "Sakamoto",
    "Endo",
  ],
  states: [
    "Hokkaido",
    "Aomori",
    "Iwate",
    "Miyagi",
    "Akita",
    "Yamagata",
    "Fukushima",
    "Ibaraki",
    "Tochigi",
    "Gunma",
    "Saitama",
    "Chiba",
    "Tokyo",
    "Kanagawa",
    "Niigata",
    "Toyama",
    "Ishikawa",
    "Fukui",
    "Yamanashi",
    "Nagano",
    "Gifu",
    "Shizuoka",
    "Aichi",
    "Mie",
    "Shiga",
    "Kyoto",
    "Osaka",
    "Hyogo",
    "Nara",
    "Wakayama",
    "Tottori",
    "Shimane",
    "Okayama",
    "Hiroshima",
    "Yamaguchi",
    "Tokushima",
    "Kagawa",
    "Ehime",
    "Kochi",
    "Fukuoka",
    "Saga",
    "Nagasaki",
    "Kumamoto",
    "Oita",
    "Miyazaki",
    "Kagoshima",
    "Okinawa",
  ],
  cities: [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Kawasaki",
    "Saitama",
    "Hiroshima",
    "Sendai",
    "Chiba",
    "Kitakyushu",
    "Sakai",
    "Niigata",
    "Hamamatsu",
    "Shizuoka",
    "Okayama",
    "Kumamoto",
    "Kagoshima",
    "Matsuyama",
    "Nagasaki",
    "Oita",
    "Kanazawa",
  ],
  domains: ["gmail.com", "yahoo.co.jp", "outlook.jp", "icloud.com", "ezweb.ne.jp", "docomo.ne.jp"],
  phoneMask: "0XX-XXXX-XXXX",
  postalCodeMask: "XXX-XXXX",
  fieldI18nKeys: {},
  docs: {
    myNumber: { generate: () => `${pad(12)}`, mono: true },
  },
};

function pad(n: number): string {
  return String(Math.floor(Math.random() * Math.pow(10, n))).padStart(n, "0");
}

export default jp;
